# Generated by Django 5.2.11 on 2026-03-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi Empresa S.A.', max_length=150)),
                ('cif', models.CharField(default='A12345678B', max_length=20)),
                ('direccion', models.CharField(default='Calle Principal, 1', max_length=255)),
                ('iva_general', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
            ],
        ),
    ]
